from pathlib import Path
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")


# ============================================================
# PATHS
# ============================================================

SILVER_DIR = Path("processed/silver")
GOLD_DIR = Path("processed/gold")
SUMMARY_DIR = Path("summaries")

GOLD_DIR.mkdir(parents=True, exist_ok=True)
SUMMARY_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# HELPERS
# ============================================================

def read_csv_safely(path: Path) -> pd.DataFrame:
    try:
        return pd.read_csv(path, low_memory=False)
    except Exception:
        return pd.read_csv(path, engine="python", low_memory=False)


def find_required_file(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path


def find_optional_file(paths: list[Path]) -> Path | None:
    for path in paths:
        if path.exists():
            return path
    return None


def safe_mode(x):
    mode_val = x.dropna().mode()
    if len(mode_val) > 0:
        return mode_val.iloc[0]
    return np.nan


def safe_percentile(x, q):
    values = pd.to_numeric(x, errors="coerce").dropna()
    if len(values) == 0:
        return np.nan
    return np.percentile(values, q)


def safe_divide(numerator, denominator, default=0):
    result = numerator / denominator.replace(0, np.nan)
    result = result.replace([np.inf, -np.inf], np.nan)
    return result.fillna(default)


def standardize_year_month(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if "Year" in df.columns:
        df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")

    if "Month" in df.columns:
        df["Month"] = pd.to_numeric(df["Month"], errors="coerce").astype("Int64")

    return df


def fill_numeric(df: pd.DataFrame, cols: list[str], fill_value=0) -> pd.DataFrame:
    df = df.copy()

    for col in cols:
        if col in df.columns:
            df[col] = (
                pd.to_numeric(df[col], errors="coerce")
                .replace([np.inf, -np.inf], np.nan)
                .fillna(fill_value)
            )

    return df


def clean_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace(r"\s+", "_", regex=True)
    )
    return df


def normalize_holiday_columns(holidays: pd.DataFrame) -> pd.DataFrame:
    """
    The latest holiday script creates corrected unique-date-level columns.
    This function also keeps compatibility with older alias names if they exist.
    """
    holidays = clean_columns(holidays)

    rename_map = {
        "holiday_record_count": "holiday_classification_count",
        "public_holiday_count": "public_holiday_date_count",
        "bank_holiday_count": "bank_holiday_date_count",
        "mercantile_holiday_count": "mercantile_holiday_date_count",
        "poya_day_count": "poya_day_date_count",
        "weekend_holiday_count": "weekend_holiday_date_count",
        "long_weekend_holiday_count": "long_weekend_holiday_date_count",
        "festive_holiday_count": "festive_holiday_date_count",
    }

    for old_col, new_col in rename_map.items():
        if new_col not in holidays.columns and old_col in holidays.columns:
            holidays[new_col] = holidays[old_col]

    required_holiday_cols = [
        "holiday_date_count",
        "holiday_classification_count",
        "public_holiday_date_count",
        "bank_holiday_date_count",
        "mercantile_holiday_date_count",
        "poya_day_date_count",
        "weekend_holiday_date_count",
        "long_weekend_holiday_date_count",
        "festive_holiday_date_count",
        "holiday_intensity_score",
    ]

    for col in required_holiday_cols:
        if col not in holidays.columns:
            holidays[col] = 0
        holidays[col] = pd.to_numeric(holidays[col], errors="coerce").fillna(0)

    return holidays


def load_population_density() -> pd.DataFrame:
    """
    Reads monthly population density generated by scripts/6.API.py.

    Expected possible columns:
    - location_name or Outlet_ID
    - year / Year
    - month_num / Month or month
    - base_population
    - monthly_density
    - mobility_factor
    - tourism_factor
    - province
    - country
    - pop_source
    """
    density_path = find_optional_file([
        Path("monthly_density.csv"),
        SILVER_DIR / "monthly_density.csv",
        GOLD_DIR / "monthly_density.csv",
    ])

    if density_path is None:
        print("Population density file not found. Gold will continue without density features.")
        return pd.DataFrame(columns=["Outlet_ID"])

    print("Loading population density:", density_path)

    density = read_csv_safely(density_path)
    density = clean_columns(density)

    if "location_name" in density.columns and "Outlet_ID" not in density.columns:
        density = density.rename(columns={"location_name": "Outlet_ID"})

    if "Outlet_ID" not in density.columns:
        raise ValueError("Population density file must contain Outlet_ID or location_name.")

    # Convert possible year/month formats.
    if "Year" not in density.columns and "year" in density.columns:
        density["Year"] = density["year"]

    if "Month" not in density.columns and "month_num" in density.columns:
        density["Month"] = density["month_num"]

    if "Month" not in density.columns and "month" in density.columns:
        parsed_month = pd.to_datetime(density["month"], errors="coerce")
        density["Year"] = parsed_month.dt.year
        density["Month"] = parsed_month.dt.month

    density = standardize_year_month(density)

    numeric_cols = [
        "base_population",
        "monthly_density",
        "mobility_factor",
        "tourism_factor",
    ]

    density = fill_numeric(density, numeric_cols, np.nan)

    if "monthly_density" not in density.columns:
        raise ValueError("Population density file does not contain monthly_density.")

    return density


# ============================================================
# LOAD INPUTS
# ============================================================

def load_inputs():
    # Use imputed outlet master if available. Do not impute again here.
    outlet_master_path = find_optional_file([
        SILVER_DIR / "outlet_master_imputed.csv",
        SILVER_DIR / "outlet_master_imputed_with_flags.csv",
        SILVER_DIR / "outlet_master_silver.csv",
    ])

    if outlet_master_path is None:
        raise FileNotFoundError(
            "Could not find outlet master file. Expected outlet_master_imputed.csv or outlet_master_silver.csv."
        )

    print("Using outlet master file:", outlet_master_path)

    outlet_coordinates_path = find_required_file(SILVER_DIR / "outlet_coordinates_silver.csv")
    transactions_sales_path = find_required_file(SILVER_DIR / "transactions_sales_silver.csv")
    transactions_returns_path = find_required_file(SILVER_DIR / "transactions_returns_silver.csv")
    holiday_monthly_path = find_required_file(SILVER_DIR / "holiday_monthly_features_silver.csv")
    seasonality_path = find_required_file(SILVER_DIR / "distributor_seasonality_silver.csv")

    return_features_path = SILVER_DIR / "transaction_return_features_silver.csv"
    billing_features_path = SILVER_DIR / "transaction_billing_anomaly_features_silver.csv"
    context_score_path = SILVER_DIR / "distributor_month_context_score_silver.csv"

    outlet_master = read_csv_safely(outlet_master_path)
    outlet_coordinates = read_csv_safely(outlet_coordinates_path)
    sales = read_csv_safely(transactions_sales_path)
    returns = read_csv_safely(transactions_returns_path)
    holidays = read_csv_safely(holiday_monthly_path)
    seasonality = read_csv_safely(seasonality_path)

    if return_features_path.exists():
        return_features = read_csv_safely(return_features_path)
    else:
        return_features = pd.DataFrame(columns=["Outlet_ID"])

    if billing_features_path.exists():
        billing_features = read_csv_safely(billing_features_path)
    else:
        billing_features = pd.DataFrame(columns=["Outlet_ID"])

    if context_score_path.exists():
        context_score = read_csv_safely(context_score_path)
    else:
        context_score = pd.DataFrame()

    population_density = load_population_density()

    return {
        "outlet_master": outlet_master,
        "outlet_coordinates": outlet_coordinates,
        "sales": sales,
        "returns": returns,
        "holidays": holidays,
        "seasonality": seasonality,
        "return_features": return_features,
        "billing_features": billing_features,
        "context_score": context_score,
        "population_density": population_density,
    }


# ============================================================
# CLEAN INPUT TYPES
# ============================================================

def clean_input_types(data: dict) -> dict:
    om = clean_columns(data["outlet_master"])
    oc = clean_columns(data["outlet_coordinates"])
    sales = clean_columns(data["sales"])
    returns = clean_columns(data["returns"])
    holidays = normalize_holiday_columns(data["holidays"])
    seasonality = clean_columns(data["seasonality"])
    return_features = clean_columns(data["return_features"])
    billing_features = clean_columns(data["billing_features"])
    context_score = clean_columns(data["context_score"]) if not data["context_score"].empty else data["context_score"]
    density = data["population_density"]

    sales = standardize_year_month(sales)
    returns = standardize_year_month(returns)
    holidays = standardize_year_month(holidays)
    seasonality = standardize_year_month(seasonality)

    if not context_score.empty:
        context_score = standardize_year_month(context_score)

    if not density.empty:
        density = standardize_year_month(density)

    for col in ["Volume_Liters", "Total_Bill_Value", "Price_Per_Liter"]:
        if col in sales.columns:
            sales[col] = pd.to_numeric(sales[col], errors="coerce")
        if col in returns.columns:
            returns[col] = pd.to_numeric(returns[col], errors="coerce")

    if "Cooler_Count" in om.columns:
        om["Cooler_Count"] = pd.to_numeric(om["Cooler_Count"], errors="coerce")

    for col in ["Latitude", "Longitude"]:
        if col in oc.columns:
            oc[col] = pd.to_numeric(oc[col], errors="coerce")

    if "seasonality_score" in seasonality.columns:
        seasonality["seasonality_score"] = pd.to_numeric(
            seasonality["seasonality_score"], errors="coerce"
        ).fillna(0)
    else:
        seasonality["seasonality_score"] = seasonality["Seasonality_Index"].map({
            "Favorable": 1,
            "Moderate": 0,
            "Un-Favorable": -1,
        }).fillna(0)

    if "seasonality_multiplier" in seasonality.columns:
        seasonality["seasonality_multiplier"] = pd.to_numeric(
            seasonality["seasonality_multiplier"], errors="coerce"
        ).fillna(1.0)
    else:
        seasonality["seasonality_multiplier"] = seasonality["Seasonality_Index"].map({
            "Favorable": 1.10,
            "Moderate": 1.00,
            "Un-Favorable": 0.90,
        }).fillna(1.0)

    data["outlet_master"] = om
    data["outlet_coordinates"] = oc
    data["sales"] = sales
    data["returns"] = returns
    data["holidays"] = holidays
    data["seasonality"] = seasonality
    data["return_features"] = return_features
    data["billing_features"] = billing_features
    data["context_score"] = context_score
    data["population_density"] = density

    return data


# ============================================================
# MONTHLY SALES GOLD
# ============================================================

def build_monthly_sales_gold(
    sales: pd.DataFrame,
    holidays: pd.DataFrame,
    seasonality: pd.DataFrame,
    context_score: pd.DataFrame,
    density: pd.DataFrame
):
    monthly_sales = (
        sales
        .groupby(["Outlet_ID", "Year", "Month"])
        .agg(
            monthly_liters=("Volume_Liters", "sum"),
            monthly_bill_value=("Total_Bill_Value", "sum"),
            monthly_sku_count=("SKU_ID", "nunique"),
            monthly_avg_price_per_liter=("Price_Per_Liter", "mean"),
            monthly_transaction_count=("Outlet_ID", "count")
        )
        .reset_index()
    )

    monthly_sales["Month_Index"] = monthly_sales["Year"] * 12 + monthly_sales["Month"]

    latest_month_index = monthly_sales["Month_Index"].max()

    monthly_sales["is_recent_3_months"] = (
        monthly_sales["Month_Index"] >= latest_month_index - 2
    ).astype(int)

    monthly_sales["is_recent_6_months"] = (
        monthly_sales["Month_Index"] >= latest_month_index - 5
    ).astype(int)

    # Main distributor per outlet.
    main_distributor = (
        sales
        .groupby("Outlet_ID")
        .agg(
            Distributor_ID=("Distributor_ID", safe_mode),
            distributor_count=("Distributor_ID", "nunique")
        )
        .reset_index()
    )

    monthly_sales = monthly_sales.merge(
        main_distributor,
        on="Outlet_ID",
        how="left"
    )

    # Merge corrected holiday features.
    holiday_cols = [
        "Year",
        "Month",
        "Year_Month",
        "holiday_date_count",
        "holiday_classification_count",
        "public_holiday_date_count",
        "bank_holiday_date_count",
        "mercantile_holiday_date_count",
        "poya_day_date_count",
        "weekend_holiday_date_count",
        "long_weekend_holiday_date_count",
        "festive_holiday_date_count",
        "holiday_intensity_score",
    ]

    holiday_cols = [c for c in holiday_cols if c in holidays.columns]

    monthly_sales = monthly_sales.merge(
        holidays[holiday_cols],
        on=["Year", "Month"],
        how="left"
    )

    holiday_numeric_cols = [
        "holiday_date_count",
        "holiday_classification_count",
        "public_holiday_date_count",
        "bank_holiday_date_count",
        "mercantile_holiday_date_count",
        "poya_day_date_count",
        "weekend_holiday_date_count",
        "long_weekend_holiday_date_count",
        "festive_holiday_date_count",
        "holiday_intensity_score",
    ]

    monthly_sales = fill_numeric(monthly_sales, holiday_numeric_cols, 0)

    # Merge distributor seasonality.
    seasonality_cols = [
        "Distributor_ID",
        "Year",
        "Month",
        "Seasonality_Index",
        "seasonality_score",
        "seasonality_multiplier",
    ]

    seasonality_cols = [c for c in seasonality_cols if c in seasonality.columns]

    monthly_sales = monthly_sales.merge(
        seasonality[seasonality_cols],
        on=["Distributor_ID", "Year", "Month"],
        how="left"
    )

    monthly_sales["Seasonality_Index"] = monthly_sales["Seasonality_Index"].fillna("Moderate")
    monthly_sales["seasonality_score"] = pd.to_numeric(
        monthly_sales["seasonality_score"], errors="coerce"
    ).fillna(0)
    monthly_sales["seasonality_multiplier"] = pd.to_numeric(
        monthly_sales["seasonality_multiplier"], errors="coerce"
    ).fillna(1.0)

    # Merge distributor-month context score if created by 6.holiday.py.
    if not context_score.empty:
        context_cols = [
            "Distributor_ID",
            "Year",
            "Month",
            "seasonality_multiplier_calibrated",
            "seasonality_multiplier_source",
            "distributor_month_demand_context_score",
            "distributor_month_context_score_0_100",
            "is_favorable_holiday_month",
            "is_unfavorable_holiday_month",
            "is_festive_favorable_month",
        ]

        context_cols = [c for c in context_cols if c in context_score.columns]

        monthly_sales = monthly_sales.merge(
            context_score[context_cols],
            on=["Distributor_ID", "Year", "Month"],
            how="left"
        )

    if "seasonality_multiplier_calibrated" not in monthly_sales.columns:
        monthly_sales["seasonality_multiplier_calibrated"] = monthly_sales["seasonality_multiplier"]

    monthly_sales["seasonality_multiplier_calibrated"] = pd.to_numeric(
        monthly_sales["seasonality_multiplier_calibrated"],
        errors="coerce"
    ).fillna(monthly_sales["seasonality_multiplier"])

    if "seasonality_multiplier_source" not in monthly_sales.columns:
        monthly_sales["seasonality_multiplier_source"] = "seasonality_default"

    if "distributor_month_demand_context_score" not in monthly_sales.columns:
        monthly_sales["distributor_month_demand_context_score"] = (
            monthly_sales["holiday_intensity_score"]
            * monthly_sales["seasonality_multiplier_calibrated"]
        )

    monthly_sales["distributor_month_demand_context_score"] = pd.to_numeric(
        monthly_sales["distributor_month_demand_context_score"],
        errors="coerce"
    ).fillna(
        monthly_sales["holiday_intensity_score"]
        * monthly_sales["seasonality_multiplier_calibrated"]
    )

    monthly_sales["seasonality_adjusted_holiday_score"] = (
        monthly_sales["holiday_intensity_score"]
        * monthly_sales["seasonality_multiplier_calibrated"]
    )

    if "is_favorable_holiday_month" not in monthly_sales.columns:
        monthly_sales["is_favorable_holiday_month"] = (
            (monthly_sales["holiday_intensity_score"] > 0)
            & (monthly_sales["Seasonality_Index"] == "Favorable")
        ).astype(int)

    if "is_unfavorable_holiday_month" not in monthly_sales.columns:
        monthly_sales["is_unfavorable_holiday_month"] = (
            (monthly_sales["holiday_intensity_score"] > 0)
            & (monthly_sales["Seasonality_Index"] == "Un-Favorable")
        ).astype(int)

    if "is_festive_favorable_month" not in monthly_sales.columns:
        monthly_sales["is_festive_favorable_month"] = (
            (monthly_sales["festive_holiday_date_count"] > 0)
            & (monthly_sales["Seasonality_Index"] == "Favorable")
        ).astype(int)

    # Merge monthly population density if available.
    if not density.empty and {"Outlet_ID", "Year", "Month", "monthly_density"}.issubset(density.columns):
        density_cols = [
            "Outlet_ID",
            "Year",
            "Month",
            "base_population",
            "monthly_density",
            "mobility_factor",
            "tourism_factor",
            "province",
        ]

        density_cols = [c for c in density_cols if c in density.columns]

        monthly_sales = monthly_sales.merge(
            density[density_cols],
            on=["Outlet_ID", "Year", "Month"],
            how="left"
        )
    else:
        monthly_sales["base_population"] = np.nan
        monthly_sales["monthly_density"] = np.nan
        monthly_sales["mobility_factor"] = np.nan
        monthly_sales["tourism_factor"] = np.nan
        monthly_sales["province"] = np.nan

    return monthly_sales, main_distributor


# ============================================================
# OUTLET-LEVEL FEATURE ENGINEERING
# ============================================================

def build_outlet_transaction_features(monthly_sales: pd.DataFrame, sales: pd.DataFrame, returns: pd.DataFrame, main_distributor: pd.DataFrame):
    outlet_features = (
        monthly_sales
        .groupby("Outlet_ID")
        .agg(
            avg_monthly_liters=("monthly_liters", "mean"),
            median_monthly_liters=("monthly_liters", "median"),
            max_monthly_liters=("monthly_liters", "max"),
            p75_monthly_liters=("monthly_liters", lambda x: safe_percentile(x, 75)),
            p90_monthly_liters=("monthly_liters", lambda x: safe_percentile(x, 90)),
            sales_std=("monthly_liters", "std"),
            total_liters=("monthly_liters", "sum"),

            avg_bill_value=("monthly_bill_value", "mean"),
            max_bill_value=("monthly_bill_value", "max"),
            total_bill_value=("monthly_bill_value", "sum"),

            avg_sku_count=("monthly_sku_count", "mean"),
            max_sku_count=("monthly_sku_count", "max"),
            avg_transaction_count=("monthly_transaction_count", "mean"),
            total_transaction_count=("monthly_transaction_count", "sum"),
            avg_price_per_liter=("monthly_avg_price_per_liter", "mean"),
            active_months=("monthly_liters", "count"),

            avg_holiday_intensity_score=("holiday_intensity_score", "mean"),
            max_holiday_intensity_score=("holiday_intensity_score", "max"),
            avg_public_holiday_date_count=("public_holiday_date_count", "mean"),
            avg_poya_day_date_count=("poya_day_date_count", "mean"),
            avg_festive_holiday_date_count=("festive_holiday_date_count", "mean"),
            avg_long_weekend_holiday_date_count=("long_weekend_holiday_date_count", "mean"),

            avg_seasonality_score=("seasonality_score", "mean"),
            avg_seasonality_multiplier=("seasonality_multiplier", "mean"),
            avg_seasonality_multiplier_calibrated=("seasonality_multiplier_calibrated", "mean"),
            avg_seasonality_adjusted_holiday_score=("seasonality_adjusted_holiday_score", "mean"),
            max_seasonality_adjusted_holiday_score=("seasonality_adjusted_holiday_score", "max"),

            avg_distributor_month_context_score=("distributor_month_demand_context_score", "mean"),
            max_distributor_month_context_score=("distributor_month_demand_context_score", "max"),

            favorable_holiday_month_count=("is_favorable_holiday_month", "sum"),
            unfavorable_holiday_month_count=("is_unfavorable_holiday_month", "sum"),
            festive_favorable_month_count=("is_festive_favorable_month", "sum"),

            avg_base_population=("base_population", "mean"),
            max_base_population=("base_population", "max"),
            avg_monthly_density=("monthly_density", "mean"),
            max_monthly_density=("monthly_density", "max"),
            avg_mobility_factor=("mobility_factor", "mean"),
            avg_tourism_factor=("tourism_factor", "mean"),
            province=("province", safe_mode),
        )
        .reset_index()
    )

    outlet_features["sales_cv"] = (
        outlet_features["sales_std"]
        / outlet_features["avg_monthly_liters"].replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan)

    recent_3 = (
        monthly_sales[monthly_sales["is_recent_3_months"] == 1]
        .groupby("Outlet_ID")
        .agg(
            recent_3_month_avg_liters=("monthly_liters", "mean"),
            recent_3_month_total_liters=("monthly_liters", "sum")
        )
        .reset_index()
    )

    recent_6 = (
        monthly_sales[monthly_sales["is_recent_6_months"] == 1]
        .groupby("Outlet_ID")
        .agg(
            recent_6_month_avg_liters=("monthly_liters", "mean"),
            recent_6_month_total_liters=("monthly_liters", "sum")
        )
        .reset_index()
    )

    january_features = (
        monthly_sales[monthly_sales["Month"] == 1]
        .groupby("Outlet_ID")
        .agg(
            avg_january_liters=("monthly_liters", "mean"),
            max_january_liters=("monthly_liters", "max"),
            avg_january_bill_value=("monthly_bill_value", "mean"),
            avg_january_sku_count=("monthly_sku_count", "mean"),
            avg_january_density=("monthly_density", "mean"),
            max_january_density=("monthly_density", "max"),
            avg_january_context_score=("distributor_month_demand_context_score", "mean"),
            avg_january_adjusted_holiday_score=("seasonality_adjusted_holiday_score", "mean"),
        )
        .reset_index()
    )

    sku_features = (
        sales
        .groupby("Outlet_ID")
        .agg(total_unique_skus=("SKU_ID", "nunique"))
        .reset_index()
    )

    normal_no_apr_dec = (
        monthly_sales[~monthly_sales["Month"].isin([4, 12])]
        .groupby("Outlet_ID")
        .agg(avg_monthly_liters_excluding_apr_dec=("monthly_liters", "mean"))
        .reset_index()
    )

    april_features = (
        monthly_sales[monthly_sales["Month"] == 4]
        .groupby("Outlet_ID")
        .agg(april_avg_liters=("monthly_liters", "mean"))
        .reset_index()
    )

    december_features = (
        monthly_sales[monthly_sales["Month"] == 12]
        .groupby("Outlet_ID")
        .agg(december_avg_liters=("monthly_liters", "mean"))
        .reset_index()
    )

    outlet_features = outlet_features.merge(recent_3, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(recent_6, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(january_features, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(sku_features, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(normal_no_apr_dec, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(april_features, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(december_features, on="Outlet_ID", how="left")
    outlet_features = outlet_features.merge(main_distributor, on="Outlet_ID", how="left")

    outlet_features["april_spike_ratio"] = (
        outlet_features["april_avg_liters"]
        / outlet_features["median_monthly_liters"].replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan).fillna(0)

    outlet_features["december_spike_ratio"] = (
        outlet_features["december_avg_liters"]
        / outlet_features["median_monthly_liters"].replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan).fillna(0)

    outlet_features["seasonal_peak_liters"] = outlet_features[
        ["april_avg_liters", "december_avg_liters"]
    ].max(axis=1)

    outlet_features["peak_to_median_ratio"] = (
        outlet_features["seasonal_peak_liters"]
        / outlet_features["median_monthly_liters"].replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan).fillna(0)

    outlet_features["seasonal_spike_flag"] = (
        outlet_features["peak_to_median_ratio"] >= 1.50
    ).astype(int)

    return_features = build_return_features(returns)

    return outlet_features, return_features


def build_return_features(returns: pd.DataFrame) -> pd.DataFrame:
    if returns.empty:
        return pd.DataFrame(columns=[
            "Outlet_ID",
            "return_record_count",
            "return_liters_abs",
            "return_value_abs",
            "return_month_count",
            "return_sku_count"
        ])

    returns = returns.copy()

    returns["return_liters_abs"] = pd.to_numeric(
        returns["Volume_Liters"], errors="coerce"
    ).abs()

    returns["return_value_abs"] = pd.to_numeric(
        returns["Total_Bill_Value"], errors="coerce"
    ).abs()

    return_features = (
        returns
        .groupby("Outlet_ID")
        .agg(
            return_record_count=("Outlet_ID", "count"),
            return_liters_abs=("return_liters_abs", "sum"),
            return_value_abs=("return_value_abs", "sum"),
            return_month_count=("Month", "nunique"),
            return_sku_count=("SKU_ID", "nunique")
        )
        .reset_index()
    )

    return return_features


# ============================================================
# BUILD OUTLET GOLD
# ============================================================

def build_outlet_gold(outlet_master, outlet_coordinates, outlet_features, return_features, billing_features):
    outlet_gold = outlet_master.merge(
        outlet_coordinates,
        on="Outlet_ID",
        how="left",
        suffixes=("", "_coord")
    )

    outlet_gold = outlet_gold.merge(
        outlet_features,
        on="Outlet_ID",
        how="left"
    )

    outlet_gold = outlet_gold.merge(
        return_features,
        on="Outlet_ID",
        how="left"
    )

    if billing_features.empty or "Outlet_ID" not in billing_features.columns:
        billing_features = pd.DataFrame(columns=[
            "Outlet_ID",
            "billing_anomaly_count",
            "zero_volume_positive_bill_count",
            "positive_volume_zero_bill_count",
            "zero_volume_zero_bill_count"
        ])

    outlet_gold = outlet_gold.merge(
        billing_features,
        on="Outlet_ID",
        how="left"
    )

    return outlet_gold


# ============================================================
# JANUARY 2026 CONTEXT
# ============================================================

def add_january_2026_context(outlet_gold, holidays, seasonality, context_score, density):
    holidays = standardize_year_month(normalize_holiday_columns(holidays))
    seasonality = standardize_year_month(seasonality)

    # 2026 January seasonality, or historical January fallback.
    jan_2026_seasonality = seasonality[
        (seasonality["Year"] == 2026)
        & (seasonality["Month"] == 1)
    ].copy()

    if len(jan_2026_seasonality) > 0:
        jan_2026_seasonality = jan_2026_seasonality[
            ["Distributor_ID", "Seasonality_Index", "seasonality_score", "seasonality_multiplier"]
        ].rename(columns={
            "Seasonality_Index": "jan_2026_seasonality_index",
            "seasonality_score": "jan_2026_seasonality_score",
            "seasonality_multiplier": "jan_2026_seasonality_multiplier"
        })
    else:
        jan_hist = seasonality[seasonality["Month"] == 1].copy()

        jan_2026_seasonality = (
            jan_hist
            .groupby("Distributor_ID")
            .agg(
                jan_2026_seasonality_index=("Seasonality_Index", safe_mode),
                jan_2026_seasonality_score=("seasonality_score", "mean"),
                jan_2026_seasonality_multiplier=("seasonality_multiplier", "mean")
            )
            .reset_index()
        )

    outlet_gold = outlet_gold.merge(
        jan_2026_seasonality,
        on="Distributor_ID",
        how="left"
    )

    outlet_gold["jan_2026_seasonality_index"] = outlet_gold["jan_2026_seasonality_index"].fillna("Moderate")
    outlet_gold["jan_2026_seasonality_score"] = pd.to_numeric(
        outlet_gold["jan_2026_seasonality_score"], errors="coerce"
    ).fillna(0)
    outlet_gold["jan_2026_seasonality_multiplier"] = pd.to_numeric(
        outlet_gold["jan_2026_seasonality_multiplier"], errors="coerce"
    ).fillna(1.0)

    # Use calibrated January context multiplier if context file exists.
    if not context_score.empty:
        context_score = standardize_year_month(context_score)

        jan_context = context_score[
            (context_score["Year"] == 2026)
            & (context_score["Month"] == 1)
        ].copy()

        if len(jan_context) == 0:
            jan_context = context_score[context_score["Month"] == 1].copy()
            jan_context = (
                jan_context
                .groupby("Distributor_ID")
                .agg(
                    jan_2026_seasonality_multiplier_calibrated=("seasonality_multiplier_calibrated", "mean"),
                    jan_2026_distributor_month_context_score=("distributor_month_demand_context_score", "mean")
                )
                .reset_index()
            )
        else:
            jan_context = jan_context[
                [
                    "Distributor_ID",
                    "seasonality_multiplier_calibrated",
                    "distributor_month_demand_context_score"
                ]
            ].rename(columns={
                "seasonality_multiplier_calibrated": "jan_2026_seasonality_multiplier_calibrated",
                "distributor_month_demand_context_score": "jan_2026_distributor_month_context_score"
            })

        outlet_gold = outlet_gold.merge(
            jan_context,
            on="Distributor_ID",
            how="left"
        )
    else:
        outlet_gold["jan_2026_seasonality_multiplier_calibrated"] = np.nan
        outlet_gold["jan_2026_distributor_month_context_score"] = np.nan

    outlet_gold["jan_2026_seasonality_multiplier_used"] = pd.to_numeric(
        outlet_gold["jan_2026_seasonality_multiplier_calibrated"],
        errors="coerce"
    ).fillna(outlet_gold["jan_2026_seasonality_multiplier"])

    # January 2026 holiday proxy.
    jan_holiday_2026 = holidays[
        (holidays["Year"] == 2026)
        & (holidays["Month"] == 1)
    ].copy()

    if len(jan_holiday_2026) > 0:
        jan_proxy = jan_holiday_2026.drop(
            columns=["Year", "Month", "Year_Month"],
            errors="ignore"
        ).mean(numeric_only=True)
    else:
        jan_proxy = (
            holidays[holidays["Month"] == 1]
            .drop(columns=["Year", "Month", "Year_Month"], errors="ignore")
            .mean(numeric_only=True)
        )

    proxy_map = {
        "holiday_intensity_score": "jan_2026_holiday_intensity_proxy",
        "holiday_date_count": "jan_2026_holiday_date_count_proxy",
        "public_holiday_date_count": "jan_2026_public_holiday_date_count_proxy",
        "poya_day_date_count": "jan_2026_poya_day_date_count_proxy",
        "festive_holiday_date_count": "jan_2026_festive_holiday_date_count_proxy",
        "long_weekend_holiday_date_count": "jan_2026_long_weekend_holiday_date_count_proxy",
    }

    for source_col, target_col in proxy_map.items():
        outlet_gold[target_col] = float(jan_proxy.get(source_col, 0))

    outlet_gold["jan_2026_adjusted_holiday_score_proxy"] = (
        outlet_gold["jan_2026_holiday_intensity_proxy"]
        * outlet_gold["jan_2026_seasonality_multiplier_used"]
    )

    # January 2026 population-density context.
    if not density.empty and {"Outlet_ID", "Year", "Month", "monthly_density"}.issubset(density.columns):
        density = standardize_year_month(density)

        jan_2026_density = density[
            (density["Year"] == 2026)
            & (density["Month"] == 1)
        ].copy()

        if len(jan_2026_density) > 0:
            jan_density_features = (
                jan_2026_density
                .groupby("Outlet_ID")
                .agg(
                    jan_2026_monthly_density=("monthly_density", "mean"),
                    jan_2026_base_population=("base_population", "mean"),
                    jan_2026_mobility_factor=("mobility_factor", "mean"),
                    jan_2026_tourism_factor=("tourism_factor", "mean"),
                )
                .reset_index()
            )
        else:
            jan_density_features = (
                density[density["Month"] == 1]
                .groupby("Outlet_ID")
                .agg(
                    jan_2026_monthly_density=("monthly_density", "mean"),
                    jan_2026_base_population=("base_population", "mean"),
                    jan_2026_mobility_factor=("mobility_factor", "mean"),
                    jan_2026_tourism_factor=("tourism_factor", "mean"),
                )
                .reset_index()
            )

        outlet_gold = outlet_gold.merge(
            jan_density_features,
            on="Outlet_ID",
            how="left"
        )
    else:
        outlet_gold["jan_2026_monthly_density"] = np.nan
        outlet_gold["jan_2026_base_population"] = np.nan
        outlet_gold["jan_2026_mobility_factor"] = np.nan
        outlet_gold["jan_2026_tourism_factor"] = np.nan

    return outlet_gold


# ============================================================
# FINAL CLEANING AND SAVE
# ============================================================

def final_clean_and_save(monthly_sales, outlet_features, outlet_gold):
    numeric_zero_cols = [
        "avg_monthly_liters",
        "median_monthly_liters",
        "max_monthly_liters",
        "p75_monthly_liters",
        "p90_monthly_liters",
        "sales_std",
        "sales_cv",
        "total_liters",
        "avg_bill_value",
        "max_bill_value",
        "total_bill_value",
        "avg_sku_count",
        "max_sku_count",
        "avg_transaction_count",
        "total_transaction_count",
        "avg_price_per_liter",
        "active_months",
        "recent_3_month_avg_liters",
        "recent_3_month_total_liters",
        "recent_6_month_avg_liters",
        "recent_6_month_total_liters",
        "avg_january_liters",
        "max_january_liters",
        "avg_january_bill_value",
        "avg_january_sku_count",
        "avg_monthly_liters_excluding_apr_dec",
        "april_avg_liters",
        "december_avg_liters",
        "april_spike_ratio",
        "december_spike_ratio",
        "seasonal_peak_liters",
        "peak_to_median_ratio",
        "seasonal_spike_flag",
        "total_unique_skus",
        "distributor_count",
        "return_record_count",
        "return_liters_abs",
        "return_value_abs",
        "return_month_count",
        "return_sku_count",
        "billing_anomaly_count",
        "zero_volume_positive_bill_count",
        "positive_volume_zero_bill_count",
        "zero_volume_zero_bill_count",
        "avg_holiday_intensity_score",
        "max_holiday_intensity_score",
        "avg_public_holiday_date_count",
        "avg_poya_day_date_count",
        "avg_festive_holiday_date_count",
        "avg_long_weekend_holiday_date_count",
        "avg_seasonality_score",
        "avg_seasonality_multiplier",
        "avg_seasonality_multiplier_calibrated",
        "avg_seasonality_adjusted_holiday_score",
        "max_seasonality_adjusted_holiday_score",
        "avg_distributor_month_context_score",
        "max_distributor_month_context_score",
        "favorable_holiday_month_count",
        "unfavorable_holiday_month_count",
        "festive_favorable_month_count",
        "avg_base_population",
        "max_base_population",
        "avg_monthly_density",
        "max_monthly_density",
        "avg_january_density",
        "max_january_density",
        "avg_january_context_score",
        "avg_january_adjusted_holiday_score",
        "avg_mobility_factor",
        "avg_tourism_factor",
        "jan_2026_seasonality_score",
        "jan_2026_seasonality_multiplier",
        "jan_2026_seasonality_multiplier_calibrated",
        "jan_2026_seasonality_multiplier_used",
        "jan_2026_distributor_month_context_score",
        "jan_2026_holiday_intensity_proxy",
        "jan_2026_holiday_date_count_proxy",
        "jan_2026_public_holiday_date_count_proxy",
        "jan_2026_poya_day_date_count_proxy",
        "jan_2026_festive_holiday_date_count_proxy",
        "jan_2026_long_weekend_holiday_date_count_proxy",
        "jan_2026_adjusted_holiday_score_proxy",
        "jan_2026_monthly_density",
        "jan_2026_base_population",
        "jan_2026_mobility_factor",
        "jan_2026_tourism_factor",
    ]

    outlet_gold = fill_numeric(outlet_gold, numeric_zero_cols, 0)

    outlet_gold["return_ratio_liters"] = (
        outlet_gold["return_liters_abs"]
        / outlet_gold["total_liters"].replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan).fillna(0)

    outlet_gold["return_ratio_value"] = (
        outlet_gold["return_value_abs"]
        / outlet_gold["total_bill_value"].replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan).fillna(0)

    outlet_gold["has_return_flag"] = (
        outlet_gold["return_record_count"] > 0
    ).astype(int)

    outlet_gold["has_billing_anomaly_flag"] = (
        outlet_gold["billing_anomaly_count"] > 0
    ).astype(int)

    if "Latitude" in outlet_gold.columns and "Longitude" in outlet_gold.columns:
        outlet_gold["missing_coordinate_flag"] = (
            outlet_gold["Latitude"].isna()
            | outlet_gold["Longitude"].isna()
        ).astype(int)
    else:
        outlet_gold["missing_coordinate_flag"] = 1

    for col in [
        "Outlet_Size",
        "Outlet_Type",
        "Distributor_ID",
        "province",
        "country",
        "pop_source",
        "jan_2026_seasonality_index",
    ]:
        if col in outlet_gold.columns:
            outlet_gold[col] = outlet_gold[col].fillna("Unknown").astype(str)

    monthly_sales.to_csv(GOLD_DIR / "monthly_sales_gold.csv", index=False)
    outlet_features.to_csv(GOLD_DIR / "outlet_transaction_features_gold.csv", index=False)
    outlet_gold.to_csv(GOLD_DIR / "outlet_features_gold.csv", index=False)

    modeling_exclude_cols = [
        "Latitude_Original",
        "Longitude_Original",
    ]

    modeling_gold = outlet_gold.drop(columns=modeling_exclude_cols, errors="ignore").copy()

    modeling_gold.to_csv(GOLD_DIR / "outlet_modeling_table_gold.csv", index=False)

    missing_report = (
        outlet_gold
        .isna()
        .sum()
        .reset_index()
        .rename(columns={"index": "column", 0: "missing_count"})
    )

    missing_report["missing_ratio"] = missing_report["missing_count"] / len(outlet_gold)

    missing_report.to_csv(SUMMARY_DIR / "gold_missing_value_report.csv", index=False)

    readiness = {
        "outlet_gold_rows": len(outlet_gold),
        "unique_outlet_count": outlet_gold["Outlet_ID"].nunique(),
        "duplicate_outlet_rows": int(outlet_gold["Outlet_ID"].duplicated().sum()),
        "monthly_sales_gold_rows": len(monthly_sales),
        "missing_outlet_size_rows": int(outlet_gold["Outlet_Size"].isna().sum()) if "Outlet_Size" in outlet_gold.columns else -1,
        "missing_coordinate_rows": int(outlet_gold["missing_coordinate_flag"].sum()),
        "population_density_available_rows": int(outlet_gold["avg_monthly_density"].gt(0).sum()) if "avg_monthly_density" in outlet_gold.columns else 0,
        "jan_2026_density_available_rows": int(outlet_gold["jan_2026_monthly_density"].gt(0).sum()) if "jan_2026_monthly_density" in outlet_gold.columns else 0,
        "context_score_available_rows": int(outlet_gold["avg_distributor_month_context_score"].gt(0).sum()) if "avg_distributor_month_context_score" in outlet_gold.columns else 0,
        "gold_ready_one_row_per_outlet": bool(outlet_gold["Outlet_ID"].nunique() == len(outlet_gold)),
    }

    pd.DataFrame([readiness]).to_csv(
        SUMMARY_DIR / "gold_pipeline_summary.csv",
        index=False
    )

    pd.DataFrame([readiness]).to_csv(
        SUMMARY_DIR / "gold_modeling_readiness_report.csv",
        index=False
    )

    print("\nGold data integration completed successfully.")
    print("Saved:")
    print("-", GOLD_DIR / "monthly_sales_gold.csv")
    print("-", GOLD_DIR / "outlet_transaction_features_gold.csv")
    print("-", GOLD_DIR / "outlet_features_gold.csv")
    print("-", GOLD_DIR / "outlet_modeling_table_gold.csv")
    print("-", SUMMARY_DIR / "gold_missing_value_report.csv")
    print("-", SUMMARY_DIR / "gold_pipeline_summary.csv")


# ============================================================
# MAIN
# ============================================================

def run_gold_data_pipeline():
    data = load_inputs()
    data = clean_input_types(data)

    monthly_sales, main_distributor = build_monthly_sales_gold(
        sales=data["sales"],
        holidays=data["holidays"],
        seasonality=data["seasonality"],
        context_score=data["context_score"],
        density=data["population_density"]
    )

    outlet_transaction_features, return_features = build_outlet_transaction_features(
        monthly_sales=monthly_sales,
        sales=data["sales"],
        returns=data["returns"],
        main_distributor=main_distributor
    )

    # Prefer return features generated fresh from transaction return rows.
    outlet_gold = build_outlet_gold(
        outlet_master=data["outlet_master"],
        outlet_coordinates=data["outlet_coordinates"],
        outlet_features=outlet_transaction_features,
        return_features=return_features,
        billing_features=data["billing_features"]
    )

    outlet_gold = add_january_2026_context(
        outlet_gold=outlet_gold,
        holidays=data["holidays"],
        seasonality=data["seasonality"],
        context_score=data["context_score"],
        density=data["population_density"]
    )

    final_clean_and_save(
        monthly_sales=monthly_sales,
        outlet_features=outlet_transaction_features,
        outlet_gold=outlet_gold
    )


if __name__ == "__main__":
    run_gold_data_pipeline()